/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Menu;

import java.awt.Color;

/**
 *
 * @author Jose Prieto
 */
public class MiembrosPannel extends javax.swing.JPanel {
    /**
     * Creates new form MainOptionPannel
     */
    public MiembrosPannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ActClub = new javax.swing.JButton();
        NuevoClub = new javax.swing.JButton();
        FichaClub = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(193, 512));

        ActClub.setBackground(new java.awt.Color(153, 153, 153));
        ActClub.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ActClub.setForeground(new java.awt.Color(204, 204, 204));
        ActClub.setText("Cambiar de club");
        ActClub.setContentAreaFilled(false);
        ActClub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActClubMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActClubMouseExited(evt);
            }
        });
        ActClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActClubActionPerformed(evt);
            }
        });

        NuevoClub.setBackground(new java.awt.Color(51, 51, 51));
        NuevoClub.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NuevoClub.setForeground(new java.awt.Color(204, 204, 204));
        NuevoClub.setText("Registrar miembro");
        NuevoClub.setBorderPainted(false);
        NuevoClub.setContentAreaFilled(false);
        NuevoClub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NuevoClub.setIconTextGap(0);
        NuevoClub.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NuevoClub.setMaximumSize(new java.awt.Dimension(125, 25));
        NuevoClub.setMinimumSize(new java.awt.Dimension(125, 25));
        NuevoClub.setPreferredSize(new java.awt.Dimension(125, 25));
        NuevoClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NuevoClubMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NuevoClubMouseExited(evt);
            }
        });
        NuevoClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoClubActionPerformed(evt);
            }
        });

        FichaClub.setBackground(new java.awt.Color(153, 153, 153));
        FichaClub.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FichaClub.setForeground(new java.awt.Color(204, 204, 204));
        FichaClub.setText("Desuscribir");
        FichaClub.setContentAreaFilled(false);
        FichaClub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FichaClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FichaClubMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FichaClubMouseExited(evt);
            }
        });
        FichaClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FichaClubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NuevoClub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ActClub, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(FichaClub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NuevoClub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ActClub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(FichaClub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        NuevoClub.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void ActClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActClubActionPerformed

    private void NuevoClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoClubActionPerformed

    private void NuevoClubMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoClubMouseEntered
        // TODO add your handling code here:
        NuevoClub.setContentAreaFilled(true);
        NuevoClub.setBackground(Color.DARK_GRAY);
        
    }//GEN-LAST:event_NuevoClubMouseEntered

    private void NuevoClubMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoClubMouseExited
        // TODO add your handling code here:
        NuevoClub.setContentAreaFilled(false);
    }//GEN-LAST:event_NuevoClubMouseExited

    private void ActClubMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActClubMouseEntered
        // TODO add your handling code here:
        ActClub.setContentAreaFilled(true);
        ActClub.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_ActClubMouseEntered

    private void ActClubMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActClubMouseExited
        // TODO add your handling code here:
        ActClub.setContentAreaFilled(false);
    }//GEN-LAST:event_ActClubMouseExited

    private void FichaClubMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FichaClubMouseEntered
        // TODO add your handling code here:
        FichaClub.setContentAreaFilled(true);
        FichaClub.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_FichaClubMouseEntered

    private void FichaClubMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FichaClubMouseExited
        // TODO add your handling code here:
        FichaClub.setContentAreaFilled(false);
    }//GEN-LAST:event_FichaClubMouseExited

    private void FichaClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FichaClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FichaClubActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ActClub;
    public javax.swing.JButton FichaClub;
    public javax.swing.JButton NuevoClub;
    // End of variables declaration//GEN-END:variables
}
