/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OperatorInterfaces.Options;

import java.awt.Color;

/**
 *
 * @author Jose Prieto
 */
public class ClubesPannel extends javax.swing.JPanel {
    /**
     * Creates new form MainOptionPannel
     */
    public ClubesPannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Libros = new javax.swing.JButton();
        Clubes = new javax.swing.JButton();
        Miembros = new javax.swing.JButton();
        Grupos = new javax.swing.JButton();
        Pagos = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(193, 512));

        Libros.setBackground(new java.awt.Color(153, 153, 153));
        Libros.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Libros.setForeground(new java.awt.Color(204, 204, 204));
        Libros.setText("Libros");
        Libros.setContentAreaFilled(false);
        Libros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LibrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LibrosMouseExited(evt);
            }
        });
        Libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrosActionPerformed(evt);
            }
        });

        Clubes.setBackground(new java.awt.Color(51, 51, 51));
        Clubes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Clubes.setForeground(new java.awt.Color(204, 204, 204));
        Clubes.setText("Clubes");
        Clubes.setBorderPainted(false);
        Clubes.setContentAreaFilled(false);
        Clubes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clubes.setIconTextGap(0);
        Clubes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Clubes.setMaximumSize(new java.awt.Dimension(125, 25));
        Clubes.setMinimumSize(new java.awt.Dimension(125, 25));
        Clubes.setPreferredSize(new java.awt.Dimension(125, 25));
        Clubes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClubesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClubesMouseExited(evt);
            }
        });
        Clubes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClubesActionPerformed(evt);
            }
        });

        Miembros.setBackground(new java.awt.Color(153, 153, 153));
        Miembros.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Miembros.setForeground(new java.awt.Color(204, 204, 204));
        Miembros.setText("Miembros");
        Miembros.setContentAreaFilled(false);
        Miembros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Miembros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MiembrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MiembrosMouseExited(evt);
            }
        });
        Miembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiembrosActionPerformed(evt);
            }
        });

        Grupos.setBackground(new java.awt.Color(153, 153, 153));
        Grupos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Grupos.setForeground(new java.awt.Color(204, 204, 204));
        Grupos.setText("Grupos");
        Grupos.setContentAreaFilled(false);
        Grupos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Grupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GruposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GruposMouseExited(evt);
            }
        });
        Grupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GruposActionPerformed(evt);
            }
        });

        Pagos.setBackground(new java.awt.Color(153, 153, 153));
        Pagos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Pagos.setForeground(new java.awt.Color(204, 204, 204));
        Pagos.setText("Pagos");
        Pagos.setContentAreaFilled(false);
        Pagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PagosMouseExited(evt);
            }
        });
        Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Clubes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Libros, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(Miembros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Pagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Grupos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Clubes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Libros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Miembros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Grupos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        Clubes.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void LibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibrosActionPerformed

    private void ClubesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClubesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClubesActionPerformed

    private void ClubesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClubesMouseEntered
        // TODO add your handling code here:
        Clubes.setContentAreaFilled(true);
        Clubes.setBackground(Color.DARK_GRAY);
        
    }//GEN-LAST:event_ClubesMouseEntered

    private void ClubesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClubesMouseExited
        // TODO add your handling code here:
        Clubes.setContentAreaFilled(false);
    }//GEN-LAST:event_ClubesMouseExited

    private void LibrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrosMouseEntered
        // TODO add your handling code here:
        Libros.setContentAreaFilled(true);
        Libros.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_LibrosMouseEntered

    private void LibrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrosMouseExited
        // TODO add your handling code here:
        Libros.setContentAreaFilled(false);
    }//GEN-LAST:event_LibrosMouseExited

    private void MiembrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiembrosMouseEntered
        // TODO add your handling code here:
        Miembros.setContentAreaFilled(true);
        Miembros.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_MiembrosMouseEntered

    private void MiembrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiembrosMouseExited
        // TODO add your handling code here:
        Miembros.setContentAreaFilled(false);
    }//GEN-LAST:event_MiembrosMouseExited

    private void PagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PagosMouseEntered
        // TODO add your handling code here:
        Pagos.setContentAreaFilled(true);
        Pagos.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_PagosMouseEntered

    private void PagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PagosMouseExited
        // TODO add your handling code here:
        Pagos.setContentAreaFilled(false);
    }//GEN-LAST:event_PagosMouseExited

    private void PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PagosActionPerformed

    private void GruposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GruposMouseEntered
        // TODO add your handling code here:
        Grupos.setContentAreaFilled(true);
        Grupos.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_GruposMouseEntered

    private void GruposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GruposMouseExited
        // TODO add your handling code here:
        Grupos.setContentAreaFilled(false);
    }//GEN-LAST:event_GruposMouseExited

    private void GruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GruposActionPerformed

    private void MiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiembrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiembrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Clubes;
    public javax.swing.JButton Grupos;
    public javax.swing.JButton Libros;
    public javax.swing.JButton Miembros;
    public javax.swing.JButton Pagos;
    // End of variables declaration//GEN-END:variables
}
