/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OperatorInterfaces.Options;

import java.awt.Color;

/**
 *
 * @author Jose Prieto
 */
public class MainOptionPannel extends javax.swing.JPanel {
    /**
     * Creates new form MainOptionPannel
     */
    public MainOptionPannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BorrowButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        ReportGenButton = new javax.swing.JButton();
        NotificationButton = new javax.swing.JButton();
        QueryButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        BorrowButton.setBackground(new java.awt.Color(153, 153, 153));
        BorrowButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BorrowButton.setForeground(new java.awt.Color(204, 204, 204));
        BorrowButton.setText("Gestión de Préstamos");
        BorrowButton.setContentAreaFilled(false);
        BorrowButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BorrowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BorrowButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BorrowButtonMouseExited(evt);
            }
        });
        BorrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowButtonActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(51, 51, 51));
        AddButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddButton.setForeground(new java.awt.Color(204, 204, 204));
        AddButton.setText("Agregar Material");
        AddButton.setBorder(null);
        AddButton.setBorderPainted(false);
        AddButton.setContentAreaFilled(false);
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddButtonMouseExited(evt);
            }
        });
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        ReportGenButton.setBackground(new java.awt.Color(153, 153, 153));
        ReportGenButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ReportGenButton.setForeground(new java.awt.Color(204, 204, 204));
        ReportGenButton.setText("Generar Reportes");
        ReportGenButton.setContentAreaFilled(false);
        ReportGenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReportGenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportGenButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportGenButtonMouseExited(evt);
            }
        });

        NotificationButton.setBackground(new java.awt.Color(153, 153, 153));
        NotificationButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NotificationButton.setForeground(new java.awt.Color(204, 204, 204));
        NotificationButton.setText("Notificaciones");
        NotificationButton.setContentAreaFilled(false);
        NotificationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NotificationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NotificationButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NotificationButtonMouseExited(evt);
            }
        });

        QueryButton.setBackground(new java.awt.Color(153, 153, 153));
        QueryButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QueryButton.setForeground(new java.awt.Color(204, 204, 204));
        QueryButton.setText("Consultar Material");
        QueryButton.setContentAreaFilled(false);
        QueryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QueryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QueryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QueryButtonMouseExited(evt);
            }
        });
        QueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BorrowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(ReportGenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NotificationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QueryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BorrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ReportGenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(NotificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QueryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BorrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrowButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed

    private void QueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QueryButtonActionPerformed

    private void AddButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseEntered
        // TODO add your handling code here:
        AddButton.setContentAreaFilled(true);
        AddButton.setBackground(Color.DARK_GRAY);
        
    }//GEN-LAST:event_AddButtonMouseEntered

    private void AddButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseExited
        // TODO add your handling code here:
        AddButton.setContentAreaFilled(false);
    }//GEN-LAST:event_AddButtonMouseExited

    private void BorrowButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrowButtonMouseEntered
        // TODO add your handling code here:
        BorrowButton.setContentAreaFilled(true);
        BorrowButton.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_BorrowButtonMouseEntered

    private void BorrowButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrowButtonMouseExited
        // TODO add your handling code here:
        BorrowButton.setContentAreaFilled(false);
    }//GEN-LAST:event_BorrowButtonMouseExited

    private void ReportGenButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportGenButtonMouseEntered
        // TODO add your handling code here:
        ReportGenButton.setContentAreaFilled(true);
        ReportGenButton.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_ReportGenButtonMouseEntered

    private void ReportGenButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportGenButtonMouseExited
        // TODO add your handling code here:
        ReportGenButton.setContentAreaFilled(false);
    }//GEN-LAST:event_ReportGenButtonMouseExited

    private void NotificationButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificationButtonMouseEntered
        // TODO add your handling code here:
        NotificationButton.setContentAreaFilled(true);
        NotificationButton.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_NotificationButtonMouseEntered

    private void NotificationButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificationButtonMouseExited
        // TODO add your handling code here:
        NotificationButton.setContentAreaFilled(false);
    }//GEN-LAST:event_NotificationButtonMouseExited

    private void QueryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueryButtonMouseEntered
        // TODO add your handling code here:
        QueryButton.setContentAreaFilled(true);
        QueryButton.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_QueryButtonMouseEntered

    private void QueryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueryButtonMouseExited
        // TODO add your handling code here:
        QueryButton.setContentAreaFilled(false);
    }//GEN-LAST:event_QueryButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AddButton;
    public javax.swing.JButton BorrowButton;
    public javax.swing.JButton NotificationButton;
    public javax.swing.JButton QueryButton;
    public javax.swing.JButton ReportGenButton;
    // End of variables declaration//GEN-END:variables
}
