/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OperatorInterfaces.Options;

import java.awt.Color;

/**
 *
 * @author Jose Prieto
 */
public class MainOptionPannel extends javax.swing.JPanel {
    /**
     * Creates new form MainOptionPannel
     */
    public MainOptionPannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdmReuniones = new javax.swing.JButton();
        AdmClubes = new javax.swing.JButton();
        AdmObras = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(193, 512));

        AdmReuniones.setBackground(new java.awt.Color(153, 153, 153));
        AdmReuniones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdmReuniones.setForeground(new java.awt.Color(204, 204, 204));
        AdmReuniones.setText("Adm. de reuniones");
        AdmReuniones.setContentAreaFilled(false);
        AdmReuniones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AdmReuniones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdmReunionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdmReunionesMouseExited(evt);
            }
        });
        AdmReuniones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmReunionesActionPerformed(evt);
            }
        });

        AdmClubes.setBackground(new java.awt.Color(51, 51, 51));
        AdmClubes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdmClubes.setForeground(new java.awt.Color(204, 204, 204));
        AdmClubes.setText("Adm. de clubes");
        AdmClubes.setBorder(null);
        AdmClubes.setBorderPainted(false);
        AdmClubes.setContentAreaFilled(false);
        AdmClubes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AdmClubes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdmClubesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdmClubesMouseExited(evt);
            }
        });
        AdmClubes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmClubesActionPerformed(evt);
            }
        });

        AdmObras.setBackground(new java.awt.Color(153, 153, 153));
        AdmObras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdmObras.setForeground(new java.awt.Color(204, 204, 204));
        AdmObras.setText("Adm. de obras actuadas");
        AdmObras.setContentAreaFilled(false);
        AdmObras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AdmObras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdmObrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdmObrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdmClubes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AdmReuniones, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(AdmObras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdmClubes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdmReuniones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdmObras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdmReunionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmReunionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdmReunionesActionPerformed

    private void AdmClubesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmClubesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdmClubesActionPerformed

    private void AdmClubesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmClubesMouseEntered
        // TODO add your handling code here:
        AdmClubes.setContentAreaFilled(true);
        AdmClubes.setBackground(Color.DARK_GRAY);
        
    }//GEN-LAST:event_AdmClubesMouseEntered

    private void AdmClubesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmClubesMouseExited
        // TODO add your handling code here:
        AdmClubes.setContentAreaFilled(false);
    }//GEN-LAST:event_AdmClubesMouseExited

    private void AdmReunionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmReunionesMouseEntered
        // TODO add your handling code here:
        AdmReuniones.setContentAreaFilled(true);
        AdmReuniones.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_AdmReunionesMouseEntered

    private void AdmReunionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmReunionesMouseExited
        // TODO add your handling code here:
        AdmReuniones.setContentAreaFilled(false);
    }//GEN-LAST:event_AdmReunionesMouseExited

    private void AdmObrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmObrasMouseEntered
        // TODO add your handling code here:
        AdmObras.setContentAreaFilled(true);
        AdmObras.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_AdmObrasMouseEntered

    private void AdmObrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmObrasMouseExited
        // TODO add your handling code here:
        AdmObras.setContentAreaFilled(false);
    }//GEN-LAST:event_AdmObrasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AdmClubes;
    public javax.swing.JButton AdmObras;
    public javax.swing.JButton AdmReuniones;
    // End of variables declaration//GEN-END:variables
}
