/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Interfaces.Menu.AdmClubesPannel;
import Interfaces.Menu.ClubesPannel;
import Interfaces.Menu.MainOptionPannel;
import Interfaces.Menu.MantLibrosPannel;
import Interfaces.Menu.ObrasPannel;
import Interfaces.Menu.ReunionesPannel;
import Interfaces.Menu.MiembrosPannel;

import Interfaces.Titulos.BorrowNamePannel;

import Interfaces.Contenido.AddMaterialContentPannel;
import Interfaces.Contenido.BorrowContentPannel;
import Interfaces.Contenido.ReturnPannel;
import Interfaces.Contenido.ConsultPannel;
import Interfaces.Contenido.NuevoClubContent;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
//import javax.swing.ImageIcon;


/**
 *
 * @author Jose Prieto
 */
public class MainWindow extends javax.swing.JFrame implements ActionListener{
    
    //Tittle pannels
    BorrowNamePannel borrowname = new BorrowNamePannel();
    
    //Menu pannels
    MainOptionPannel option = new MainOptionPannel();
    ReunionesPannel reuniones = new ReunionesPannel();
    ClubesPannel clubes = new ClubesPannel ();
    ObrasPannel obras = new ObrasPannel ();
    AdmClubesPannel admclubes = new AdmClubesPannel ();
    MantLibrosPannel libros = new MantLibrosPannel ();
    MiembrosPannel miembros = new MiembrosPannel ();
    
    //Content pannels
    AddMaterialContentPannel addcontent = new AddMaterialContentPannel();
    BorrowContentPannel borrowcontent = new BorrowContentPannel();
    ReturnPannel returncontent = new ReturnPannel();
    ConsultPannel consultcontent = new ConsultPannel();
    NuevoClubContent nuevoclub = new NuevoClubContent ();

    public MainWindow() {        
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("../Images/Icono.png")).getImage());
        
        OptionPannel.add(option);
        ContentPannel.add(addcontent);
        TitlePannel.add(borrowname);
        borrowname.jLabel1.setText("Principal");
        
        //action listener de botones de clubes
        clubes.Clubes.addActionListener(this);
        clubes.Libros.addActionListener(this);
        clubes.Miembros.addActionListener(this);
        
        //action listener de botones de admclubes
        admclubes.NuevoClub.addActionListener(this);
        admclubes.ActClub.addActionListener(this);
        admclubes.FichaClub.addActionListener(this);
        admclubes.ListaNegra.addActionListener(this);
        admclubes.EliminarClub.addActionListener(this);
        
        //action listener de botones de borrow manager pannel
        reuniones.Asistencias.addActionListener(this);
        reuniones.Calendario.addActionListener(this);
        
        //action listener de botones de option main pannel
        option.Reuniones.addActionListener(this);
        option.Clubes.addActionListener(this);
        option.Obras.addActionListener(this);
        
        //action listener de depot button
        HomeButton.addActionListener(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionPannel = new javax.swing.JPanel();
        TitlePannel = new javax.swing.JPanel();
        HomeButtonPannel = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        ContentPannel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clubes de lectura");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(102, 102, 102, 102));
        setMaximizedBounds(new java.awt.Rectangle(900, 600, 0, 0));
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        OptionPannel.setBackground(new java.awt.Color(51, 51, 51));
        OptionPannel.setForeground(new java.awt.Color(102, 102, 102));
        OptionPannel.setLayout(new java.awt.BorderLayout());

        TitlePannel.setBackground(new java.awt.Color(255, 255, 255));
        TitlePannel.setLayout(new java.awt.BorderLayout());

        HomeButtonPannel.setBackground(new java.awt.Color(51, 51, 51));
        HomeButtonPannel.setPreferredSize(new java.awt.Dimension(210, 210));

        HomeButton.setBackground(new java.awt.Color(255, 255, 255));
        HomeButton.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono.png"))); // NOI18N
        HomeButton.setBorder(null);
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        HomeButton.setMaximumSize(new java.awt.Dimension(70, 34));
        HomeButton.setMinimumSize(new java.awt.Dimension(70, 34));
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeButtonPannelLayout = new javax.swing.GroupLayout(HomeButtonPannel);
        HomeButtonPannel.setLayout(HomeButtonPannelLayout);
        HomeButtonPannelLayout.setHorizontalGroup(
            HomeButtonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        HomeButtonPannelLayout.setVerticalGroup(
            HomeButtonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeButtonPannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ContentPannel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HomeButtonPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(OptionPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitlePannel, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                    .addComponent(ContentPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HomeButtonPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(OptionPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitlePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ContentPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(916, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPannel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JPanel HomeButtonPannel;
    private javax.swing.JPanel OptionPannel;
    private javax.swing.JPanel TitlePannel;
    // End of variables declaration//GEN-END:variables

    public void SetInvisibleContent(){
        addcontent.setVisible(false);
        borrowcontent.setVisible(false);
        returncontent.setVisible(false);
        consultcontent.setVisible(false);
        
        
    }
    
    public void SetInvisibleMenu(){
        
        option.setVisible(false);
        reuniones.setVisible(false);
        clubes.setVisible(false);
        obras.setVisible(false);
        admclubes.setVisible(false);
        libros.setVisible(false);
        miembros.setVisible(false);
        
    }
    
    @Override
    public void actionPerformed(ActionEvent ae) {
        Object evt = ae.getSource();
        
        if (evt.equals(option.Reuniones)){

            SetInvisibleMenu();
            SetInvisibleContent();
            
            reuniones.setVisible(true);
            borrowcontent.setVisible(true);
            
            OptionPannel.validate();
            ContentPannel.validate();
            
            ContentPannel.add(borrowcontent);
            borrowname.jLabel1.setText("Cierre de reunión");
            OptionPannel.add(reuniones);

        }else if (evt.equals(HomeButton)){
            
            SetInvisibleMenu();
            SetInvisibleContent();
            
            option.setVisible(true);
            addcontent.setVisible(true);
            
            OptionPannel.validate();
            ContentPannel.validate();
            
            OptionPannel.add(option);
            borrowname.jLabel1.setText("Principal");
            ContentPannel.add(addcontent);
            
        }else if (evt.equals(option.Obras)){
            
            SetInvisibleMenu();
            SetInvisibleContent();
            
            obras.setVisible(true);
            addcontent.setVisible(true);
            
            OptionPannel.validate();
            ContentPannel.validate();
            
            OptionPannel.add(obras);
            borrowname.jLabel1.setText("Administración de obras");
            ContentPannel.add(addcontent);
            
        }else if (evt.equals(option.Clubes)){
            
            SetInvisibleMenu();
            SetInvisibleContent();
            
            clubes.setVisible(true);
            borrowcontent.setVisible(true);
            
            OptionPannel.validate();
            ContentPannel.validate();
            
            ContentPannel.add(borrowcontent);
            borrowname.jLabel1.setText("Pagos");
            OptionPannel.add(clubes);
            
        }else if (evt.equals(clubes.Clubes)){
            
            SetInvisibleMenu();
            SetInvisibleContent();
            
            admclubes.setVisible(true);
            nuevoclub.setVisible(true);
            
            OptionPannel.validate();
            ContentPannel.validate();
            
            ContentPannel.add(nuevoclub);
            borrowname.jLabel1.setText("Nuevo club");
            OptionPannel.add(admclubes);
            
        }else if (evt.equals(clubes.Miembros)){
            
            SetInvisibleMenu();
            SetInvisibleContent();
            
            miembros.setVisible(true);
            borrowcontent.setVisible(true);
            
            OptionPannel.validate();
            ContentPannel.validate();
            
            ContentPannel.add(borrowcontent);
            OptionPannel.add(miembros);
            
        }else if (evt.equals(clubes.Libros)){
            
            SetInvisibleMenu();
            SetInvisibleContent();
            
            libros.setVisible(true);
            borrowcontent.setVisible(true);
            
            OptionPannel.validate();
            ContentPannel.validate();
            
            ContentPannel.add(borrowcontent);
            OptionPannel.add(libros);
        }else if (evt.equals(admclubes.NuevoClub)){
            
            SetInvisibleMenu();
            SetInvisibleContent();
            
            admclubes.setVisible(true);
            nuevoclub.setVisible(true);
            
            OptionPannel.validate();
            ContentPannel.validate();
            
            ContentPannel.add(nuevoclub);
            borrowname.jLabel1.setText("Nuevo club");
            OptionPannel.add(admclubes);
            
        }
    }
}