/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OperatorInterfaces;

import OperatorInterfaces.Options.BorrowManagerPannel;
import OperatorInterfaces.Options.MainOptionPannel;

import OperatorInterfaces.Tittles.AddMaterialNamePannel;
import OperatorInterfaces.Tittles.BorrowNamePannel;
import OperatorInterfaces.Tittles.ConsultMaterialNamePannel;
import OperatorInterfaces.Tittles.ReturnMaterialNamePannel;

import OperatorInterfaces.Content.AddMaterialContentPannel;
import OperatorInterfaces.Content.BorrowContentPannel;
import OperatorInterfaces.Content.ReturnPannel;
import OperatorInterfaces.Content.ConsultPannel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author Jose Prieto
 */
public class MainWindow extends javax.swing.JFrame implements ActionListener{
    
    //Tittle pannels
    AddMaterialNamePannel addname = new AddMaterialNamePannel();
    BorrowNamePannel borrowname = new BorrowNamePannel();
    ConsultMaterialNamePannel consultname = new ConsultMaterialNamePannel();
    ReturnMaterialNamePannel returnname = new ReturnMaterialNamePannel();
    
    //Menu pannels
    MainOptionPannel option = new MainOptionPannel();
    BorrowManagerPannel borrow = new BorrowManagerPannel();
    
    //Content pannels
    AddMaterialContentPannel addcontent = new AddMaterialContentPannel();
    BorrowContentPannel borrowcontent = new BorrowContentPannel();
    ReturnPannel returncontent = new ReturnPannel();
    ConsultPannel consultcontent = new ConsultPannel();

    public MainWindow() {
        
        initComponents();
        
        OptionPannel.add(option);
        TitlePannel.add(addname);
        ContentPannel.add(addcontent);
        
        //action listener de botones de borrow manager pannel
        borrow.ReturnButton.addActionListener(this);
        borrow.BorrowButton.addActionListener(this);
        
        //action listener de botones de option main pannel
        option.BorrowButton.addActionListener(this);
        option.AddButton.addActionListener(this);
        option.NotificationButton.addActionListener(this);
        option.QueryButton.addActionListener(this);
        option.ReportGenButton.addActionListener(this);
        
        //action listener de depot button
        HomeButton.addActionListener(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionPannel = new javax.swing.JPanel();
        TitlePannel = new javax.swing.JPanel();
        HomeButtonPannel = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        ContentPannel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Depot");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximizedBounds(new java.awt.Rectangle(900, 600, 0, 0));
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));

        OptionPannel.setBackground(new java.awt.Color(51, 51, 51));
        OptionPannel.setForeground(new java.awt.Color(102, 102, 102));
        OptionPannel.setLayout(new java.awt.BorderLayout());

        TitlePannel.setBackground(new java.awt.Color(255, 255, 255));
        TitlePannel.setLayout(new java.awt.BorderLayout());

        HomeButtonPannel.setBackground(new java.awt.Color(51, 51, 51));
        HomeButtonPannel.setPreferredSize(new java.awt.Dimension(210, 210));

        HomeButton.setBackground(new java.awt.Color(255, 255, 255));
        HomeButton.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_depot.png"))); // NOI18N
        HomeButton.setBorder(null);
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        HomeButton.setMaximumSize(new java.awt.Dimension(70, 34));
        HomeButton.setMinimumSize(new java.awt.Dimension(70, 34));

        javax.swing.GroupLayout HomeButtonPannelLayout = new javax.swing.GroupLayout(HomeButtonPannel);
        HomeButtonPannel.setLayout(HomeButtonPannelLayout);
        HomeButtonPannelLayout.setHorizontalGroup(
            HomeButtonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        HomeButtonPannelLayout.setVerticalGroup(
            HomeButtonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeButtonPannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ContentPannel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HomeButtonPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(OptionPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitlePannel, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                    .addComponent(ContentPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HomeButtonPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(OptionPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitlePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ContentPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(916, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPannel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JPanel HomeButtonPannel;
    private javax.swing.JPanel OptionPannel;
    private javax.swing.JPanel TitlePannel;
    // End of variables declaration//GEN-END:variables

    public void SetInvisibleContent(){
        addcontent.setVisible(false);
        borrowcontent.setVisible(false);
        returncontent.setVisible(false);
        consultcontent.setVisible(false);
        
    }
    
    public void SetInvisibleTittle(){
        
        addname.setVisible(false);
        borrowname.setVisible(false);
        consultname.setVisible(false);
        returnname.setVisible(false);
        
    }
    
    public void SetInvisibleMenu(){
        
        option.setVisible(false);
        borrow.setVisible(false);
        
    }
    
    @Override
    public void actionPerformed(ActionEvent ae) {
        Object evt = ae.getSource();
        
        if (evt.equals(option.BorrowButton)){

            SetInvisibleTittle();
            SetInvisibleMenu();
            SetInvisibleContent();
            
            borrow.setVisible(true);
            borrowname.setVisible(true);
            borrowcontent.setVisible(true);
            
            OptionPannel.validate();
            TitlePannel.validate();
            ContentPannel.validate();
            
            ContentPannel.add(borrowcontent);
            TitlePannel.add(borrowname);
            OptionPannel.add(borrow);

        }else if (evt.equals(HomeButton)){
            
            SetInvisibleTittle();
            SetInvisibleMenu();
            SetInvisibleContent();
            
            option.setVisible(true);
            addname.setVisible(true);
            addcontent.setVisible(true);
            
            OptionPannel.validate();
            TitlePannel.validate();
            ContentPannel.validate();
            
            OptionPannel.add(option);
            TitlePannel.add(addname);
            ContentPannel.add(addcontent);
            
        }else if (evt.equals(option.AddButton)){
            
            SetInvisibleTittle();
            SetInvisibleContent();
            
            addname.setVisible(true);
            addcontent.setVisible(true);
            
            TitlePannel.validate();
            ContentPannel.validate();
            
            TitlePannel.add(addname);
            ContentPannel.add(addcontent);
            
        }else if (evt.equals(option.QueryButton)){
            
            SetInvisibleTittle();
            SetInvisibleContent();
            
            consultname.setVisible(true);
            consultcontent.setVisible(true);
            
            TitlePannel.validate();
            ContentPannel.validate();
            
            TitlePannel.add(consultname);
            ContentPannel.add(consultcontent);
            
        }else if (evt.equals(borrow.ReturnButton)){
            
            SetInvisibleTittle();
            SetInvisibleContent();
            
            returncontent.setVisible(true);
            returnname.setVisible(true);
            
            TitlePannel.validate();
            ContentPannel.validate();
            
            TitlePannel.add(returnname);
            ContentPannel.add(returncontent);
            
        }else if (evt.equals(borrow.BorrowButton)){
            
            SetInvisibleTittle();
            SetInvisibleContent();
            
            borrowcontent.setVisible(true);
            borrowname.setVisible(true);
            
            TitlePannel.validate();
            ContentPannel.validate();
            
            TitlePannel.add(borrowname);
            ContentPannel.add(borrowcontent);
            
        }
    }
}